### ISSUE TITLE
Example - oneD

### ISSUE THREAD

**Issue by imifrenzel** [Hydrology-IFH/roger#39]
I am trying to run the oneD example as decribed in the tutorial:

**Roger runs (no errors)**
> activate roger
> python oneD.py

Three .nc files are created in the directory

**The postprocessing.py throws an error at l. 76.**
> conda install -c conda-forge xarray
> python post_processing.py

File .\miniconda3\envs\roger\lib\site-packages\xarray\core\dataset.py", line 1353, in _construct_dataarray
    variable = self._variables[name]
KeyError: 'aet'

**The state_hm.nc file seems to be empty.** 
> ds_sim = xr.open_dataset(states_hm_file, engine="h5netcdf")
> print(ds_sim)

<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
Attributes:
    date_created:     2023-04-19T16:11:44.897225
    title:            RoGeR simulations (Tutorial)
    institution:      University of Freiburg, Chair of Hydrology
    references:       
    comment:          First timestep (t=0) contains initial values. Simulatio...
    model_structure:  1D model with free drainage
    roger_version:    0+untagged.1096.g6e55c3b.dirty

Are the example files flawed?

**Comment by schwemro** [comment]
The variable "aet" is missing in the config.yml. Either add it to line 38 of config.yml or you remove "aet" in line 80 of post_processing.py. I'll fix the bug and upload the modified config.yml.
